# Generated by Django 4.2 on 2023-04-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aksesuar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandAndType', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20, null=True)),
                ('kalınlık', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('Mat', models.BooleanField(default=False)),
                ('aksesuarName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aksesuar', to='Products.aksesuar', to_field='name')),
            ],
        ),
    ]
