# Generated by Django 4.2 on 2023-05-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_price_products_m2price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='M2price',
            new_name='m2price',
        ),
    ]
